SET FOREIGN_KEY_CHECKS=0;
ALTER TABLE tb_alunos
MODIFY COLUMN id BIGINT NOT NULL;
SET FOREIGN_KEY_CHECKS=1;

ALTER TABLE tb_alunos
ADD CONSTRAINT tb_alunos_ibfk_2
FOREIGN KEY (id) REFERENCES tb_login(id) ON DELETE CASCADE ON UPDATE RESTRICT;